name: Optimize and package Datapack
on:
  push:
    tags:
      - '**'
jobs:
  packsquash:
    name: Optimize Datapack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4with:
          packsquash_version: latest # Uses the latest PackSquash release supported by the action
      - name: Download optimized pack
        uses: actions/download-artifact@v4
        with:
          name: Optimized pack
      - name: Rename zip
        run: mv pack.zip ${{ github.event.repository.name }}.zip
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}.zip
